### ISSUE TITLE
Driver capabilites

### ISSUE THREAD

**Issue by JbIPS** [back2dos/browserstack#1]
I saw that driver capabilities are mapped with an Abstract. The problem is it only takes a subset of supported capabilities.

Do you have any idea on how to support all the options? I thought we could use reflection and only make a special mapping for the `browserstack.*` keys but maybe there is a better solution.

**Comment by back2dos** [comment]
I merged your changes, so this should work now ;)

**Comment by JbIPS** [comment]
Thank you :smiley:
